<?php

use yii\helpers\Html;

$this->title = 'Farid Anuar';
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="farid-content">

    <h2><?= Html::encode($this->title) ?></h2>

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim corrupti nisi voluptates cumque fugit repellat. Molestiae vel excepturi tempora. Officia, ea placeat officiis architecto dolorum, harum nisi doloremque optio quae necessitatibus suscipit incidunt iusto? Iusto, at? Blanditiis, officia! Vero, magni, porro mollitia dicta nisi amet, cupiditate ex natus similique illo distinctio excepturi vel delectus fuga. Ut, incidunt iusto corrupti libero hic ea adipisci vero natus in, temporibus recusandae quibusdam minima quae ex nulla eum dolores dolor voluptatibus! Ipsum voluptatum explicabo voluptatibus, cumque ratione cupiditate, perferendis excepturi ex ducimus sunt, officia expedita beatae. Neque dolore sunt consequatur eum eligendi aliquid nulla ea inventore error aliquam. Eaque tempore eveniet aliquam neque. Culpa consequuntur voluptas animi sit, non tenetur aperiam sint laboriosam illo officiis autem reiciendis maxime nemo facilis, quibusdam asperiores quisquam nesciunt ea! Delectus recusandae labore voluptatibus commodi atque, incidunt, iste in asperiores obcaecati esse, repellat voluptatem natus! Nemo animi aperiam enim corporis? A, vel harum ullam maiores neque maxime autem assumenda, cupiditate, quo enim veniam animi. At harum molestias, tempora enim, in sequi ex ut dolorem dolore voluptatibus id deserunt esse suscipit, repudiandae adipisci vero ad dolores labore consequatur! Ducimus natus id nostrum ad mollitia, delectus libero. Id magni ab in ipsum at dignissimos! Iusto et eius nulla fugiat molestiae, repudiandae quo voluptate repellendus amet quia mollitia alias tenetur dignissimos, esse beatae magni voluptates reprehenderit magnam eveniet quisquam! Minima dicta, delectus sed et fugiat perspiciatis eum explicabo sunt consectetur cupiditate, voluptatem dignissimos optio adipisci earum nisi, veritatis iste aut libero. Dolor recusandae facilis veritatis, sint facere blanditiis ducimus alias aspernatur maiores. Explicabo, sint. Veritatis, illum minima ea odit temporibus magnam assumenda voluptatibus, molestias fugiat at saepe perspiciatis, mollitia voluptate deserunt corporis quo vitae voluptates fugit voluptas animi. Culpa dolores ducimus nobis ipsa deleniti debitis, error unde sed, esse incidunt inventore sunt. Ad repellat, natus accusantium hic voluptates rerum cum laboriosam aspernatur inventore facere cumque blanditiis. Quae sequi facilis sed hic nihil, tempora consequuntur. Ratione maxime enim unde fuga adipisci suscipit pariatur, saepe magni aliquid itaque architecto provident blanditiis? Doloremque quos autem explicabo repudiandae magni atque est cumque non sit optio? Beatae illo molestiae pariatur, cumque quaerat, fuga soluta placeat quae aperiam id non corporis, harum ut! Magnam adipisci eaque ut, expedita dolore nisi dicta unde numquam officia explicabo dignissimos, nemo velit in voluptatem natus possimus sapiente odit delectus nihil cupiditate deleniti omnis. Esse, neque. Neque ad quidem reiciendis eos ipsum tempora!</p>

</div>